export const Colour = {
  backgroundBlack: '#111',
  backgroundDarkGrey: '#2B2B2B ',
  backgroundMediumGrey: '#3C3C3C',
  backgroundLightGrey: '#f0f0f0',
  backgroundWhite: '#FFFFFF',
  backgroundBlue: '#006ADD',
  textWhite: '#F5F5F5',
  textLightGrey: '#AAA',
  textBlack: '#111',
  textDarkGrey: '#2B2B2B',
  textGreen: '#28A745',
  textRed: '#DC3545',
  borderDarkGrey: '#2B2B2B',
  borderLightGrey: '#E0E0E0',
};